"""add_crawl_status_to_business_profiles

Revision ID: 89aa519ee418
Revises: b8c50665f7ac
Create Date: 2026-01-27 05:27:54.083552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aa519ee418'
down_revision: Union[str, Sequence[str], None] = 'b8c50665f7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop enum if it exists (might have wrong values)
    op.execute("DROP TYPE IF EXISTS crawlstatus CASCADE")
    
    # Create enum type with correct lowercase values
    op.execute("CREATE TYPE crawlstatus AS ENUM ('not_started', 'pending', 'in_progress', 'completed', 'failed')")
    
    # Add crawl_status column as nullable (no server_default to avoid enum validation)
    op.execute("ALTER TABLE business_profiles ADD COLUMN crawl_status crawlstatus")
    
    # Update existing rows to set default value
    op.execute("UPDATE business_profiles SET crawl_status = 'not_started' WHERE crawl_status IS NULL")
    
    # Make column NOT NULL
    op.execute("ALTER TABLE business_profiles ALTER COLUMN crawl_status SET NOT NULL")
    
    # Add other columns (all nullable)
    op.add_column('business_profiles', sa.Column('crawl_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('business_profiles', sa.Column('crawl_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('business_profiles', sa.Column('crawl_error', sa.Text(), nullable=True))
    op.add_column('business_profiles', sa.Column('total_pages_crawled', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'total_pages_crawled')
    op.drop_column('business_profiles', 'crawl_error')
    op.drop_column('business_profiles', 'crawl_completed_at')
    op.drop_column('business_profiles', 'crawl_started_at')
    op.drop_column('business_profiles', 'crawl_status')
    # ### end Alembic commands ###
