"""Initial schema with 11 tables

Revision ID: b8c50665f7ac
Revises: 
Create Date: 2026-01-27 04:10:23.086429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c50665f7ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt_type', sa.Enum('ENTITY_ANALYSIS', 'SENTIMENT_ANALYSIS', 'KEYWORD_EXTRACTION', 'AUTO_REPLY', 'CONTENT_GENERATION', 'SCHEMA_VALIDATION', 'NAP_EXTRACTION', name='prompttype'), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.String(length=10), nullable=True),
    sa.Column('max_tokens', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_prompts_name'), 'geo_prompts', ['name'], unique=True)
    op.create_index(op.f('ix_geo_prompts_prompt_type'), 'geo_prompts', ['prompt_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('primary_location', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('brand_voice', sa.Text(), nullable=True),
    sa.Column('main_goal', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=False)
    op.create_table('google_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('connected_email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_connections_user_id'), 'google_connections', ['user_id'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', 'ARCHIVED', name='sessionstatus'), nullable=False),
    sa.Column('context_data', sa.Text(), nullable=True),
    sa.Column('message_count', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_business_profile_id'), 'chat_sessions', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('geo_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('geo_prompt_id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('parsed_response', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PARTIAL', name='responsestatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geo_prompt_id'], ['geo_prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_responses_business_profile_id'), 'geo_responses', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_geo_responses_geo_prompt_id'), 'geo_responses', ['geo_prompt_id'], unique=False)
    op.create_table('geo_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('entity_clarity_score', sa.Integer(), nullable=True),
    sa.Column('freshness_score', sa.Integer(), nullable=True),
    sa.Column('name_clarity', sa.Integer(), nullable=True),
    sa.Column('category_clarity', sa.Integer(), nullable=True),
    sa.Column('location_clarity', sa.Integer(), nullable=True),
    sa.Column('service_clarity', sa.Integer(), nullable=True),
    sa.Column('nap_consistency_score', sa.Integer(), nullable=True),
    sa.Column('review_sentiment_score', sa.Float(), nullable=True),
    sa.Column('review_velocity', sa.Integer(), nullable=True),
    sa.Column('schema_validity_score', sa.Integer(), nullable=True),
    sa.Column('crawl_readiness_score', sa.Integer(), nullable=True),
    sa.Column('profiles_synced', sa.Integer(), nullable=True),
    sa.Column('ai_citations', sa.Integer(), nullable=True),
    sa.Column('scoring_factors', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_scores_business_profile_id'), 'geo_scores', ['business_profile_id'], unique=True)
    op.create_table('google_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=True),
    sa.Column('google_location_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('primary_location', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('VERIFIED', 'NEEDS_ATTENTION', 'LIMITED_ACCESS', 'NOT_ELIGIBLE', name='locationstatus'), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.String(length=10), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_locations_business_profile_id'), 'google_locations', ['business_profile_id'], unique=False)
    op.create_index(op.f('ix_google_locations_google_location_id'), 'google_locations', ['google_location_id'], unique=True)
    op.create_index(op.f('ix_google_locations_user_id'), 'google_locations', ['user_id'], unique=False)
    op.create_table('website_content',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('page_type', sa.String(length=100), nullable=True),
    sa.Column('crawl_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='crawlstatus'), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('h1_tags', sa.Text(), nullable=True),
    sa.Column('h2_tags', sa.Text(), nullable=True),
    sa.Column('schema_markup', sa.Text(), nullable=True),
    sa.Column('extracted_name', sa.String(length=255), nullable=True),
    sa.Column('extracted_address', sa.Text(), nullable=True),
    sa.Column('extracted_phone', sa.String(length=50), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('entity_mentions', sa.Integer(), nullable=True),
    sa.Column('location_mentions', sa.Integer(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_content_business_profile_id'), 'website_content', ['business_profile_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chat_session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.String(length=10), nullable=True),
    sa.Column('execution_time_ms', sa.String(length=10), nullable=True),
    sa.Column('context_snapshot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_session_id'), 'chat_messages', ['chat_session_id'], unique=False)
    op.create_table('google_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('google_location_id', sa.String(length=36), nullable=False),
    sa.Column('google_review_id', sa.String(length=255), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('reviewer_photo_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentimentlabel'), nullable=True),
    sa.Column('extracted_keywords', sa.Text(), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('suggested_reply_preset', sa.String(length=50), nullable=True),
    sa.Column('owner_reply', sa.Text(), nullable=True),
    sa.Column('owner_reply_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['google_location_id'], ['google_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_reviews_google_location_id'), 'google_reviews', ['google_location_id'], unique=False)
    op.create_index(op.f('ix_google_reviews_google_review_id'), 'google_reviews', ['google_review_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_reviews_google_review_id'), table_name='google_reviews')
    op.drop_index(op.f('ix_google_reviews_google_location_id'), table_name='google_reviews')
    op.drop_table('google_reviews')
    op.drop_index(op.f('ix_chat_messages_chat_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_website_content_business_profile_id'), table_name='website_content')
    op.drop_table('website_content')
    op.drop_index(op.f('ix_google_locations_user_id'), table_name='google_locations')
    op.drop_index(op.f('ix_google_locations_google_location_id'), table_name='google_locations')
    op.drop_index(op.f('ix_google_locations_business_profile_id'), table_name='google_locations')
    op.drop_table('google_locations')
    op.drop_index(op.f('ix_geo_scores_business_profile_id'), table_name='geo_scores')
    op.drop_table('geo_scores')
    op.drop_index(op.f('ix_geo_responses_geo_prompt_id'), table_name='geo_responses')
    op.drop_index(op.f('ix_geo_responses_business_profile_id'), table_name='geo_responses')
    op.drop_table('geo_responses')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_business_profile_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_google_connections_user_id'), table_name='google_connections')
    op.drop_table('google_connections')
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_geo_prompts_prompt_type'), table_name='geo_prompts')
    op.drop_index(op.f('ix_geo_prompts_name'), table_name='geo_prompts')
    op.drop_table('geo_prompts')
    # ### end Alembic commands ###
